# Generated by Django 2.0.3 on 2018-03-18 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('date_changed', models.DateTimeField(auto_now_add=True)),
                ('family_name', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('father_name', models.CharField(max_length=250)),
                ('birth_date', models.DateField()),
                ('phone_number', models.CharField(max_length=12)),
                ('passport_number', models.CharField(max_length=10)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('partner', models.ForeignKey(limit_choices_to={'profile__is_partner': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Партнер')),
            ],
            options={
                'verbose_name': 'Анкета клиента',
                'verbose_name_plural': 'Анкеты клиентов',
            },
        ),
        migrations.CreateModel(
            name='CreditProposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('date_sent', models.DateTimeField()),
                ('status', models.PositiveSmallIntegerField(default=1, verbose_name=((1, 'новая'), (2, 'отправлена'), (3, 'получена'), (4, 'одобрена'), (5, 'отказано'), (6, 'выдано')))),
                ('client_form', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='credit.ClientForm', verbose_name='Анкета клиента')),
            ],
            options={
                'verbose_name': 'Заявка в кредитную организацию',
                'verbose_name_plural': 'Заявки в кредитные организации',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('date_changed', models.DateTimeField(auto_now_add=True)),
                ('rotation_date_begin', models.DateTimeField()),
                ('rotation_date_end', models.DateTimeField()),
                ('offer_name', models.CharField(max_length=250)),
                ('offer_type', models.PositiveSmallIntegerField(default=1, verbose_name=((1, 'потредительский кредит'), (2, 'ипотека'), (3, 'автокредит')))),
                ('min_score', models.PositiveSmallIntegerField(default=0)),
                ('max_score', models.PositiveSmallIntegerField(default=0)),
                ('credit_organization', models.ForeignKey(limit_choices_to={'profile__is_credit_organization': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Кредитная организация')),
            ],
            options={
                'verbose_name': 'Предложение',
                'verbose_name_plural': 'Предложения',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_credit_organization', models.BooleanField(default=False, verbose_name='Кредитная организация')),
                ('is_partner', models.BooleanField(default=False, verbose_name='Партнер')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователя',
            },
        ),
        migrations.AddField(
            model_name='creditproposal',
            name='offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='credit.Offer', verbose_name='Предложение'),
        ),
    ]
