# Generated by Django 2.0.3 on 2018-03-18 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0002_auto_20180318_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientform',
            name='partner',
            field=models.ForeignKey(limit_choices_to={'profile__is_partner': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Партнер'),
        ),
        migrations.AlterField(
            model_name='creditproposal',
            name='date_sent',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='credit_organization',
            field=models.ForeignKey(limit_choices_to={'profile__is_credit_organization': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Кредитная организация'),
        ),
    ]
